### PR TITLE
Translated zh-CN Chapter 6

### PR DESCRIPTION
**Pull request by kaleo996**
Finished translating Chapter 6 into zh-CN. Please review and tell me to correct if there are any mistakes 😊. @MKhalusova

### CODE REVIEW

**Comment by kaleo996** [comment]
It looks good to me now. The titles of the chapters showed in the content are currently not in a consistent style, but I have unified them with kerning in my local repo, and will open another PR to push them along with chapter7 of zh-CN a few days later. Thank you for your patience! 🙂❤

**Comment by MKhalusova** [comment]
The PR looks good to me. It would be great if @adeenayakup or someone from the community could check the translation.

**Review by Tsumugii24 — COMMENTED** [review]
Thank you for your efforts and contributions, I reviewed them all and the basicly speaking the translation is accurate, but some things are still not so natural from the perspective of a Chinese native speaker. And i will be really grateful if you can help me review the translation of my PR for Chapter8

**Review by Tsumugii24 — APPROVED** [review]

**Comment by kaleo996** [comment]
Sorry, I'm afraid that I don't have write access, so my review is not sufficient to approve your PR. /(ㄒoㄒ)/~~ @Tsumugii24

**Review by MKhalusova — APPROVED** [review]

**Comment by MKhalusova** [comment]
Thanks for the review @Tsumugii24 !

**Comment by Tsumugii24** [comment]
> Sorry, I'm afraid that I don't have write access, so my review is not sufficient to approve your PR. /(ㄒoㄒ)/~~ @Tsumugii24

maybe a simple review and approve comment may help maintainers and others know my work~

**Pull request merged**
