### PR TITLE
Added the table "Languages and translations" to README.md

### PR DESCRIPTION
**Pull request by blademoon**
@MKhalusova Good day Maria. 

Added an empty table "Languages and translations" to the README.md file. The table display was checked in VSCode, it is displayed correctly. The links to the course repository and the corresponding pages on the official HF website have also been changed.

In the next PR we will add translators' names.

### CODE REVIEW

**Comment by blademoon** [comment]
@MKhalusova All checks passed, need review.

**Comment by MKhalusova** [comment]
The table looks good, please add the authors for the Russian translation. Then we can merge.

**Comment by MKhalusova** [comment]
We can add the names in the same PR, there's no need to split it into two separate PRs

**Review by MKhalusova — APPROVED** [review]
LGTM

**Comment by blademoon** [comment]
@MKhalusova I was too late to see it. We'll make it a separate PR.

**Comment by blademoon** [comment]
@MKhalusova Thank you so much Maria for your work!

**Pull request merged**
