### PR TITLE
Chapter 2, chapter 4 translated to Russian

### PR DESCRIPTION
**Pull request by Lightmourne**

### CODE REVIEW

**Comment by blademoon** [comment]
@MKhalusova Good afternoon Maria, can you consider this PR? It would help our translation team a lot.

**Review by blademoon — APPROVED** [review]

**Review by blademoon — COMMENTED** [review]
Overall good, minor flaws will be corrected in the process of translating subsequent units.

**Review by MKhalusova — APPROVED** [review]
Thank you for working on translating these units! Great work overall. I've left a few minor comments. Once those are fixed, we can merge.

**Comment by Lightmourne** [comment]
@MKhalusova Hello Maria! Thank you for your review. I have made changes according to your comments.

**Pull request merged**
